### ISSUE TITLE
Diseño de website

### ISSUE THREAD

**Issue by alexfuser** [jorandradefig/fellowship-project-climate-change#6]
Todo lo relacionado con el diseño del sitio: Logo, diseño de landing page, tipografía, información, etc.

**Comment by alexfuser** [comment]
De los diseños que he buscado para poder adaptarlos me ha gustado estos:

http://themes.webdevia.com/ecology/#1481415355891-31bab8a5-237b

http://ecoenergy.ancorathemes.com

https://devitems.com/preview/green-soul/index-2.html

http://recycle.orionthemes.com/new-demo-1/

http://wp1.themexlab.com/newwp/podgorica/

Cual de las propuestas les gusta para iniciar con el desarrollo de la página? @puentejose @eudoxocnido

**Comment by puentejose** [comment]
El que más me gustó es: http://wp1.themexlab.com/newwp/podgorica/

**Comment by GammaOfZeta** [comment]
http://recycle.orionthemes.com/new-demo-1/

**Comment by alexfuser** [comment]
A mi también me gusta http://recycle.orionthemes.com/new-demo-1/ así que, dejamos ese entonces para hacerlo como modelo de diseño, vale? @puentejose @eudoxocnido

**Comment by alexfuser** [comment]
Bueno pues ya quedo el diseño que será http://recycle.orionthemes.com/new-demo-1/ y vamos a empezar con el desarrollo del sitio en el issue #11
